[package]
name = "russcip"
authors = ["Mohammad Ghannam <mohammad.m.ghannam@gmail.com>"]
description = "Rust interface for SCIP."
license = "Apache-2.0"
repository = "https://github.com/scipopt/russcip"
version = "0.1.13"
edition = "2021"

[features]
raw = []

[dependencies]
scip-sys =  "0.1.4"
doc-comment = "0.3.3"
