[package]
name = "russcip"
authors = ["Mohammad Ghannam <mohammad.m.ghannam@gmail.com>"]
description = "Rust interface for SCIP"
license = "Apache-2.0"
repository = "https://github.com/scipopt/russcip"
version = "0.3.1"
edition = "2021"
exclude = ["data/test/*"]

[features]
raw = []
bundled = ["scip-sys/bundled"]

[dependencies]
scip-sys =  "0.1.9"

[dev-dependencies]
rayon = "1.5.1"

[lints.clippy]
too_many_arguments = "allow"